- name: Create instance(s)
  hosts: localhost
  connection: local
  gather_facts: no

  vars:
    machine_type: n1-standard-1
    image: debian-7

  tasks:

   - name: Launch instances
     gce:
         instance_names: "test-{{ user }}-gce"
         machine_type: "{{ machine_type }}"
         image: "{{ image }}"
