- name: Collect facts from Openstack instances
  hosts: all
  vars:
  tasks:
  # Gather facts about all servers named C<web*>:
  - os_server_facts:
      timeout: 60
  - debug:
      var: openstack_instances
