- name: Collect facts from Openstack instances
  hosts: all
  vars:
  tasks:
  # Gather facts about all servers named C<web*>:
  - os_server_facts:
      timeout: 60
    environment:
      OS_PROJECT_DOMAIN_NAME: Default 
      OS_USER_DOMAIN_NAME: Default
    register: myfacts
  - debug:
      var: myfacts
