- name: Collect facts from Rackspace Cloud
  hosts: all
  gather_facts: False
  vars:
  tasks:
  - name: Get facts about servers
    local_action:
      module: rax_facts
      # name: "{{ inventory_hostname }}"
      name: miq-bot
      region: IAD
    register: myfacts

  - name: show facts
    debug:
      var=myfacts
  # - name: Map some facts
  #  set_fact:
  #    ansible_ssh_host: "{{ rax_accessipv4 }}"
